# Generated by Django 3.1.3 on 2022-06-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('assets', models.IntegerField()),
                ('income', models.IntegerField()),
                ('yield_rate', models.FloatField()),
                ('total_content', models.FloatField()),
                ('capital', models.IntegerField()),
                ('product', models.IntegerField()),
                ('range', models.CharField(max_length=1000)),
                ('Introduction', models.CharField(max_length=500)),
                ('score', models.FloatField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
