# Generated by Django 3.1.3 on 2022-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='id',
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
