# Generated by Django 3.1.3 on 2022-06-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220609_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='assets',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='capital',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='income',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='product',
            field=models.FloatField(),
        ),
    ]
