# Generated by Django 3.1.3 on 2022-06-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220609_0833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
