# Generated by Django 3.1.3 on 2022-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='assets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='capital',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='product',
            field=models.IntegerField(),
        ),
    ]
