# Generated by Django 3.1.3 on 2022-06-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rank_3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank_2',
        ),
        migrations.DeleteModel(
            name='Rank_3',
        ),
    ]
