# Generated by Django 3.1.3 on 2022-07-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20220609_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='expert_score',
            field=models.FloatField(default=0),
        ),
    ]
