# Generated by Django 3.1.3 on 2022-07-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rank_expert_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('expert_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
        ),
    ]
