# Generated by Django 3.1.3 on 2022-08-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='pos_neg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rank',
            name='profession_name',
            field=models.FloatField(default=0),
        ),
    ]
