# Generated by Django 3.2.13 on 2022-11-15 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20220802_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='公司名称')),
                ('product_num', models.IntegerField(default=0, verbose_name='产品总数')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_type', models.SmallIntegerField(choices=[(1, '工业软件仿真设计产品'), (2, '工业软件嵌入式系统产品'), (3, '工业软件生产调度和过程控制产品'), (4, '工业软件经营信息管理产品'), (5, '工业软件平台与系统产品')], verbose_name='产品类型')),
                ('pro_detail', models.CharField(max_length=1000, verbose_name='产品描述')),
                ('pro_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company', verbose_name='所属公司')),
            ],
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
    ]
