# Generated by Django 3.2.13 on 2022-11-15 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20221115_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
    ]
