# Generated by Django 3.2.13 on 2022-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_rank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='pro_id',
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_company',
            field=models.CharField(max_length=50, verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_type',
            field=models.SmallIntegerField(choices=[(1, '工业软件仿真设计产品'), (2, '工业软件嵌入式系统产品'), (3, '工业软件生产调度和过程控制产品'), (4, '工业软件经营信息管理产品'), (5, '工业软件平台与系统产品')], null=True, verbose_name='产品类型'),
        ),
    ]
