# Generated by Django 3.2.13 on 2022-11-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20221115_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='Introduction',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='income',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='pos_neg',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='profession_name',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='range',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='total_content',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='yield_rate',
        ),
        migrations.AddField(
            model_name='company',
            name='Introduction',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='assets',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='capital',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='fz_product',
            field=models.IntegerField(default=0, verbose_name='工业软件仿真设计产品个数'),
        ),
        migrations.AddField(
            model_name='company',
            name='income',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='jy_product',
            field=models.IntegerField(default=0, verbose_name='工业软件经营信息管理产品个数'),
        ),
        migrations.AddField(
            model_name='company',
            name='kz_product',
            field=models.IntegerField(default=0, verbose_name='工业软件生产调度和过程控制产品个数'),
        ),
        migrations.AddField(
            model_name='company',
            name='pos_neg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='pt_product',
            field=models.IntegerField(default=0, verbose_name='工业软件平台与系统产品个数'),
        ),
        migrations.AddField(
            model_name='company',
            name='qr_product',
            field=models.IntegerField(default=0, verbose_name='工业软件嵌入式系统产品个数'),
        ),
        migrations.AddField(
            model_name='company',
            name='range',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='total_content',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='yield_rate',
            field=models.FloatField(default=0),
        ),
    ]
