# Generated by Django 3.2.13 on 2022-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20221116_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Introduction',
            field=models.CharField(default=None, max_length=500, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='company',
            name='assets',
            field=models.FloatField(default=0, verbose_name='资产总额'),
        ),
        migrations.AlterField(
            model_name='company',
            name='capital',
            field=models.FloatField(default=0, verbose_name='注册资本'),
        ),
        migrations.AlterField(
            model_name='company',
            name='income',
            field=models.FloatField(default=0, verbose_name='营业收入'),
        ),
        migrations.AlterField(
            model_name='company',
            name='range',
            field=models.CharField(default=None, max_length=1000, verbose_name='经营范围'),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_content',
            field=models.FloatField(default=0, verbose_name='科技创新总含量'),
        ),
        migrations.AlterField(
            model_name='company',
            name='yield_rate',
            field=models.FloatField(default=0, verbose_name='净资产收益率'),
        ),
    ]
